# COW Code to PITF Code
# 
# NOTE: Assumes data frame is called 'data' and COW label is 'ccode'

 "AFG" -> data$sftgcode[data$ccode==700]
 "ALB" -> data$sftgcode[data$ccode==339]
 "ALG" -> data$sftgcode[data$ccode==615]
 "ANG" -> data$sftgcode[data$ccode==540]
 "ARG" -> data$sftgcode[data$ccode==160]
 "ARM" -> data$sftgcode[data$ccode==371]
 "AUL" -> data$sftgcode[data$ccode==900]
 "AUS" -> data$sftgcode[data$ccode==305]
 "AZE" -> data$sftgcode[data$ccode==373]
 "BAH" -> data$sftgcode[data$ccode==692]
 "BAR" -> data$sftgcode[data$ccode==53]
 "BEL" -> data$sftgcode[data$ccode==211]
 "BEN" -> data$sftgcode[data$ccode==434]
 "BFO" -> data$sftgcode[data$ccode==439]
 "BHM" -> data$sftgcode[data$ccode==31]
 "BHU" -> data$sftgcode[data$ccode==760]
 "BLR" -> data$sftgcode[data$ccode==370]
 "BLZ" -> data$sftgcode[data$ccode==80]
 "BNG" -> data$sftgcode[data$ccode==771]
 "BOL" -> data$sftgcode[data$ccode==145]
 "BOS" -> data$sftgcode[data$ccode==346]
 "BOT" -> data$sftgcode[data$ccode==571]
 "BRA" -> data$sftgcode[data$ccode==140]
 "BUI" -> data$sftgcode[data$ccode==516]
 "BUL" -> data$sftgcode[data$ccode==355]
 "CAM" -> data$sftgcode[data$ccode==811]
 "CAN" -> data$sftgcode[data$ccode==20]
 "CAO" -> data$sftgcode[data$ccode==471]
 "CEN" -> data$sftgcode[data$ccode==482]
 "CHA" -> data$sftgcode[data$ccode==483]
 "CHL" -> data$sftgcode[data$ccode==155]
 "CHN" -> data$sftgcode[data$ccode==710]
 "COL" -> data$sftgcode[data$ccode==100]
 "COM" -> data$sftgcode[data$ccode==581]
 "CON" -> data$sftgcode[data$ccode==484]
 "COS" -> data$sftgcode[data$ccode==94]
 "CRO" -> data$sftgcode[data$ccode==344]
 "CUB" -> data$sftgcode[data$ccode==40]
 "CYP" -> data$sftgcode[data$ccode==352]
 "CZE" -> data$sftgcode[data$ccode==315]
 "CZR" -> data$sftgcode[data$ccode==316]
 "DEN" -> data$sftgcode[data$ccode==390]
 "DJI" -> data$sftgcode[data$ccode==522]
 "DOM" -> data$sftgcode[data$ccode==42]
 "ZAI" -> data$sftgcode[data$ccode==490]
 "DRV" -> data$sftgcode[data$ccode==816 & data$year<=1975]
 "VIE" -> data$sftgcode[data$ccode==816 & data$year>=1976]
 "VIE" -> data$sftgcode[data$ccode==818]
 "ECU" -> data$sftgcode[data$ccode==130]
 "EGY" -> data$sftgcode[data$ccode==651]
 "EQG" -> data$sftgcode[data$ccode==411]
 "ERI" -> data$sftgcode[data$ccode==531]
 "EST" -> data$sftgcode[data$ccode==366]
 "ETH" -> data$sftgcode[data$ccode==530 & data$year<=1992]
 "ETI" -> data$sftgcode[data$ccode==530 & data$year>=1993]
 "ETH" -> data$sftgcode[data$ccode==529]
 "ETM" -> data$sftgcode[data$ccode==860]
 "FIN" -> data$sftgcode[data$ccode==375]
 "FJI" -> data$sftgcode[data$ccode==950]
 "FRN" -> data$sftgcode[data$ccode==220]
 "GAB" -> data$sftgcode[data$ccode==481]
 "GAM" -> data$sftgcode[data$ccode==420]
 "GDR" -> data$sftgcode[data$ccode==265]
 "GFR" -> data$sftgcode[data$ccode==260 & data$year<=1989]
 "GER" -> data$sftgcode[data$ccode==260 & data$year>=1990]
 "GER" -> data$sftgcode[data$ccode==255]
 "GHA" -> data$sftgcode[data$ccode==452]
 "GNB" -> data$sftgcode[data$ccode==404]
 "GRC" -> data$sftgcode[data$ccode==350]
 "GUA" -> data$sftgcode[data$ccode==90]
 "GUI" -> data$sftgcode[data$ccode==438]
 "GUY" -> data$sftgcode[data$ccode==110]
 "HAI" -> data$sftgcode[data$ccode==41]
 "HON" -> data$sftgcode[data$ccode==91]
 "HUN" -> data$sftgcode[data$ccode==310]
 "ICE" -> data$sftgcode[data$ccode==395]
 "IND" -> data$sftgcode[data$ccode==750]
 "INS" -> data$sftgcode[data$ccode==850]
 "IRE" -> data$sftgcode[data$ccode==205]
 "IRN" -> data$sftgcode[data$ccode==630]
 "IRQ" -> data$sftgcode[data$ccode==645]
 "ISR" -> data$sftgcode[data$ccode==666]
 "ITA" -> data$sftgcode[data$ccode==325]
 "JAM" -> data$sftgcode[data$ccode==51]
 "JOR" -> data$sftgcode[data$ccode==663]
 "JPN" -> data$sftgcode[data$ccode==740]
 "KEN" -> data$sftgcode[data$ccode==501]
 "KUW" -> data$sftgcode[data$ccode==690]
 "KYR" -> data$sftgcode[data$ccode==703]
 "KZK" -> data$sftgcode[data$ccode==705]
 "LAO" -> data$sftgcode[data$ccode==812]
 "LAT" -> data$sftgcode[data$ccode==367]
 "LBR" -> data$sftgcode[data$ccode==450]
 "LEB" -> data$sftgcode[data$ccode==660]
 "LES" -> data$sftgcode[data$ccode==570]
 "LIB" -> data$sftgcode[data$ccode==620]
 "LIT" -> data$sftgcode[data$ccode==368]
 "MAA" -> data$sftgcode[data$ccode==435]
 "MAC" -> data$sftgcode[data$ccode==343]
 "MAG" -> data$sftgcode[data$ccode==580]
 "MAL" -> data$sftgcode[data$ccode==820]
 "MAS" -> data$sftgcode[data$ccode==590]
 "MAW" -> data$sftgcode[data$ccode==553]
 "MEX" -> data$sftgcode[data$ccode==70]
 "MLD" -> data$sftgcode[data$ccode==359]
 "MLI" -> data$sftgcode[data$ccode==432]
 "MON" -> data$sftgcode[data$ccode==712]
 "MOR" -> data$sftgcode[data$ccode==600]
 "MYA" -> data$sftgcode[data$ccode==775]
 "MZM" -> data$sftgcode[data$ccode==541]
 "NAM" -> data$sftgcode[data$ccode==565]
 "NEP" -> data$sftgcode[data$ccode==790]
 "NEW" -> data$sftgcode[data$ccode==920]
 "NIC" -> data$sftgcode[data$ccode==93]
 "NIG" -> data$sftgcode[data$ccode==475]
 "NIR" -> data$sftgcode[data$ccode==436]
 "NOR" -> data$sftgcode[data$ccode==385]
 "NTH" -> data$sftgcode[data$ccode==210]
 "OMA" -> data$sftgcode[data$ccode==698]
 "PKS" -> data$sftgcode[data$ccode==770 & data$year<=1971]
 "PKS" -> data$sftgcode[data$ccode==769]
 "PAK" -> data$sftgcode[data$ccode==770 & data$year>=1972]
 "PAN" -> data$sftgcode[data$ccode==95]
 "PAR" -> data$sftgcode[data$ccode==150]
 "PER" -> data$sftgcode[data$ccode==135]
 "PHI" -> data$sftgcode[data$ccode==840]
 "PNG" -> data$sftgcode[data$ccode==910]
 "POL" -> data$sftgcode[data$ccode==290]
 "POR" -> data$sftgcode[data$ccode==235]
 "QAT" -> data$sftgcode[data$ccode==694]
 "ROK" -> data$sftgcode[data$ccode==732]
 "KOR" -> data$sftgcode[data$ccode==730]
 "RUM" -> data$sftgcode[data$ccode==360]
 "USS" -> data$sftgcode[data$ccode==365 & data$year<=1991 & data$year>=1917]
 "USS" -> data$sftgcode[data$ccode==364]
 "RUS" -> data$sftgcode[data$ccode==365 & (data$year>=1992 | data$year<=1916)]
 "RVN" -> data$sftgcode[data$ccode==817]
 "RWA" -> data$sftgcode[data$ccode==517]
 "SAF" -> data$sftgcode[data$ccode==560]
 "SAL" -> data$sftgcode[data$ccode==92]
 "SAU" -> data$sftgcode[data$ccode==670]
 "SEN" -> data$sftgcode[data$ccode==433]
 "SIE" -> data$sftgcode[data$ccode==451]
 "SIN" -> data$sftgcode[data$ccode==830]
 "SLO" -> data$sftgcode[data$ccode==317]
 "SLV" -> data$sftgcode[data$ccode==349]
 "SOL" -> data$sftgcode[data$ccode==940]
 "SOM" -> data$sftgcode[data$ccode==520]
 "SPN" -> data$sftgcode[data$ccode==230]
 "SRI" -> data$sftgcode[data$ccode==780]
 "SUD" -> data$sftgcode[data$ccode==625]
 "SUR" -> data$sftgcode[data$ccode==115]
 "SWA" -> data$sftgcode[data$ccode==572]
 "SWD" -> data$sftgcode[data$ccode==380]
 "SWZ" -> data$sftgcode[data$ccode==225]
 "SYR" -> data$sftgcode[data$ccode==652]
 "TAJ" -> data$sftgcode[data$ccode==702]
 "TAW" -> data$sftgcode[data$ccode==713]
 "TAZ" -> data$sftgcode[data$ccode==510]
 "THI" -> data$sftgcode[data$ccode==800]
 "TKM" -> data$sftgcode[data$ccode==701]
 "TOG" -> data$sftgcode[data$ccode==461]
 "TRI" -> data$sftgcode[data$ccode==52]
 "TUN" -> data$sftgcode[data$ccode==616]
 "TUR" -> data$sftgcode[data$ccode==640]
 "UAE" -> data$sftgcode[data$ccode==696]
 "UGA" -> data$sftgcode[data$ccode==500]
 "USA" -> data$sftgcode[data$ccode==2]
 "UK" -> data$sftgcode[data$ccode==200]
 "UKR" -> data$sftgcode[data$ccode==369]
 "URU" -> data$sftgcode[data$ccode==165]
 "UZB" -> data$sftgcode[data$ccode==704]
 "VEN" -> data$sftgcode[data$ccode==101]
 "YEM" -> data$sftgcode[data$ccode==678 & data$year>=1991]
 "YEM" -> data$sftgcode[data$ccode==679]
 "YAR" -> data$sftgcode[data$ccode==678 & data$year<=1990]
 "YPR" -> data$sftgcode[data$ccode==680]
 "YUG" -> data$sftgcode[data$ccode==345 & data$year<=1991]
 "YGS" -> data$sftgcode[data$ccode==345 & data$year>=1992 & data$year<=2006]
 "SRB" -> data$sftgcode[data$ccode==345 & data$year>=2007]
 "SRB" -> data$sftgcode[data$ccode==342]
 "MNE" -> data$sftgcode[data$ccode==348]
 "ZAM" -> data$sftgcode[data$ccode==551]
 "ZIM" -> data$sftgcode[data$ccode==552]
 "MNE" -> data$sftgcode[data$ccode==341]
 "KOS" -> data$sftgcode[data$ccode==347]
 "IVO" -> data$sftgcode[data$ccode==437]
 "PRK" -> data$sftgcode[data$ccode==731]
 "GRG" -> data$sftgcode[data$ccode==372]
