# PITF Country Code Maker
# Creates 'code' variable to match SFTGCODE in PITF Merge files.
#
# NOTE:
#       1. Target data frame must be named 'data'
#       2. Country name var must be named 'name'
#       3. Year variable must be named 'year'

data$code <- NA
data$code[data$name=="Afghanistan"] <- 'AFG'
data$code[data$name=="Albania"] <- 'ALB'
data$code[data$name=="Algeria"] <- 'ALG'
data$code[data$name=="Angola"] <- 'ANG'
data$code[data$name=="Argentina"] <- 'ARG'
data$code[data$name=="Armenia"] <- 'ARM'
data$code[data$name=="Australia"] <- 'AUL'
data$code[data$name=="Austria"] <- 'AUS'
data$code[data$name=="Azerbaijan"] <- 'AZE'
data$code[data$name=="Bahamas"] <- 'BHM'
data$code[data$name=="Bahamas, The"] <- 'BHM'
data$code[data$name=="The Bahamas"] <- 'BHM'
data$code[data$name=="Bahrain"] <- 'BAH'
data$code[data$name=="Bangladesh"] <- 'BNG'
data$code[data$name=="Barbados"] <- 'BAR'
data$code[data$name=="Belarus"] <- 'BLR'
data$code[data$name=="Belgium"] <- 'BEL'
data$code[data$name=="Belize"] <- 'BLZ'
data$code[data$name=="Benin"] <- 'BEN'
data$code[data$name=="Bhutan"] <- 'BHU'
data$code[data$name=="Bolivia"] <- 'BOL'
data$code[data$name=="Bosnia"] <- 'BOS'
data$code[data$name=="Bosnia and Herzegovina"] <- 'BOS'
data$code[data$name=="Bosnia Herzegovenia"] <- 'BOS'
data$code[data$name=="Bosnia-Herzegovina"] <- 'BOS'
data$code[data$name=="Botswana"] <- 'BOT'
data$code[data$name=="Brazil"] <- 'BRA'
data$code[data$name=="Brunei"] <- 'BRU'
data$code[data$name=="Bulgaria"] <- 'BUL'
data$code[data$name=="Burkina Faso"] <- 'BFO'
data$code[data$name=="Burma"] <- 'MYA'
data$code[data$name=="Myanmar"] <- 'MYA'
data$code[data$name=="Myanmar (Burma)"] <- 'MYA'
data$code[data$name=="Burundi"] <- 'BUI'
data$code[data$name=="Bangladesh"] <- 'BNG'
data$code[data$name=="Cambodia"] <- 'CAM'
data$code[data$name=="Cape Verde"] <- 'CAP'
data$code[data$name=="Cameroon"] <- 'CAO'
data$code[data$name=="Canada"] <- 'CAN'
data$code[data$name=="Central African Republic"] <- 'CEN'
data$code[data$name=="Cen African Rep"] <- 'CEN'
data$code[data$name=="Chad"] <- 'CHA'
data$code[data$name=="Chile"] <- 'CHL'
data$code[data$name=="China"] <- 'CHN'
data$code[data$name=="Colombia"] <- 'COL'
data$code[data$name=="Comoros"] <- 'COM'
data$code[data$name=="Congo-Brazzaville"] <- 'CON'
data$code[data$name=="Republic of Congo"] <- 'CON'
data$code[data$name=="Congo, Republic of"] <- 'CON'
data$code[data$name=="Congo (Brazzaville)"] <- 'CON'
data$code[data$name=="Republic of the Congo"] <- 'CON'
data$code[data$name=="Congo Brazzaville"] <- 'CON'
data$code[data$name=="Congo"] <- 'CON'
data$code[data$name=="Congo, Rep."] <- 'CON'
data$code[data$name=="Congo, Rep.(Brazzaville)"] <- 'CON'
data$code[data$name=="Congo-Brz"] <- 'CON'
data$code[data$name=="Congo (Brazzaville, Republic of Congo)"] <- 'CON'
data$code[data$name=="Congo-Kinshasa"] <- 'ZAI'
data$code[data$name=="Zaire"] <- 'ZAI'
data$code[data$name=="Zaire/DRC"] <- 'ZAI'
data$code[data$name=="Democratic Republic of Congo"] <- 'ZAI'
data$code[data$name=="Democratic Republic of the Congo"] <- 'ZAI'
data$code[data$name=="Congo, Democratic Republic of"] <- 'ZAI'
data$code[data$name=="Congo, Dem. Rep."] <- 'ZAI'
data$code[data$name=="Congo (Kinshasa)"] <- 'ZAI'
data$code[data$name=="Congo Kinshasa"] <- 'ZAI'
data$code[data$name=="DROC"] <- 'ZAI'
data$code[data$name=="Congo, Dem. Rep. (Zaire, Kinshasa)"] <- 'ZAI'
data$code[data$name=="Congo/Zaire"] <- 'ZAI'
data$code[data$name=="Democratic Republic of the Congo (Zaire, Congo-Kinshasha)"] <- 'ZAI'
data$code[data$name=="Costa Rica"] <- 'COS'
data$code[data$name=="Cote d'Ivoire"] <- 'IVO'
data$code[data$name=="Ivory Coast"] <- 'IVO'
data$code[data$name=="Cote d Ivoire"] <- 'IVO'
data$code[data$name=="Ivory Coast (Cote d'Ivoire)"] <- 'IVO'
data$code[data$name=="Côte d'Ivoire"] <- 'IVO'
data$code[data$name=="Croatia"] <- 'CRO'
data$code[data$name=="Cuba"] <- 'CUB'
data$code[data$name=="Cyprus"] <- 'CYP'
data$code[data$name=="Czech Republic"] <- 'CZR'
data$code[data$name=="Czechoslovakia"] <- 'CZE'
data$code[data$name=="Denmark"] <- 'DEN'
data$code[data$name=="Djibouti"] <- 'DJI'
data$code[data$name=="Dominican Republic"] <- 'DOM'
data$code[data$name=="Dominican Rep"] <- 'DOM'
data$code[data$name=="East Timor"] <- 'ETM'
data$code[data$name=="Timor"] <- 'ETM'
data$code[data$name=="Timor Leste"] <- 'ETM'
data$code[data$name=="East Timor (Timor L'este)"] <- 'ETM'
data$code[data$name=="Timor-Leste"] <- 'ETM'
data$code[data$name=="Ecuador"] <- 'ECU'
data$code[data$name=="Egypt"] <- 'EGY'
data$code[data$name=="Egypt, Arab Rep."] <- 'EGY'
data$code[data$name=="El Salvador"] <- 'SAL'
data$code[data$name=="Equatorial Guinea"] <- 'EQG'
data$code[data$name=="Eritrea"] <- 'ERI'
data$code[data$name=="Estonia"] <- 'EST'
data$code[data$name=="Ethiopia" & data$year >= 1993] <- 'ETI'
data$code[data$name=="Ethiopia" & data$year < 1993] <- 'ETH'
data$code[data$name=="Fiji"] <- 'FJI'
data$code[data$name=="Finland"] <- 'FIN'
data$code[data$name=="Finland "] <- 'FIN'
data$code[data$name=="France"] <- 'FRN'
data$code[data$name=="Estonia"] <- 'EST'
data$code[data$name=="Gabon"] <- 'GAB'
data$code[data$name=="Gambia"] <- 'GAM'
data$code[data$name=="The Gambia"] <- 'GAM'
data$code[data$name=="Gambia, the"] <- 'GAM'
data$code[data$name=="Gambia, The"] <- 'GAM'
data$code[data$name=="Georgia"] <- 'GRG'
data$code[data$name=="Germany"] <- 'GER'
data$code[data$name=="East Germany"] <- 'GDR'
data$code[data$name=="Germany, East"] <- 'GDR'
data$code[data$name=="German Democratic Republic"] <- 'GDR'
data$code[data$name=="Germany East"] <- 'GDR'
data$code[data$name=="Germany, E. "] <- 'GDR'
data$code[data$name=="West Germany"] <- 'GFR'
data$code[data$name=="Germany, West"] <- 'GFR'
data$code[data$name=="Federal Republic of Germany"] <- 'GFR'
data$code[data$name=="German Federal Republic"] <- 'GFR'
data$code[data$name=="Germany West"] <- 'GFR'
data$code[data$name=="Germany, W. "] <- 'GFR'
data$code[data$name=="Germany" & data$year < 1991] <- 'GFR'
data$code[data$name=="Ghana"] <- 'GHA'
data$code[data$name=="Greece"] <- 'GRC'
data$code[data$name=="Guatemala"] <- 'GUA'
data$code[data$name=="Guinea"] <- 'GUI'
data$code[data$name=="Guinea-Bissau"] <- 'GNB'
data$code[data$name=="Guinea Bissau"] <- 'GNB'
data$code[data$name=="West Germany"] <- 'GFR'
data$code[data$name=="Guyana"] <- 'GUY'
data$code[data$name=="Haiti"] <- 'HAI'
data$code[data$name=="Honduras"] <- 'HON'
data$code[data$name=="Hungary"] <- 'HUN'
data$code[data$name=="Iceland"] <- 'ICE'
data$code[data$name=="India"] <- 'IND'
data$code[data$name=="Indonesia"] <- 'INS'
data$code[data$name=="Guyana"] <- 'GUY'
data$code[data$name=="Iran"] <- 'IRN'
data$code[data$name=="Iran, Islamic Rep."] <- 'IRN'
data$code[data$name=="Islamic Republic of Iran"] <- 'IRN'
data$code[data$name=="Iraq"] <- 'IRQ'
data$code[data$name=="Ireland"] <- 'IRE'
data$code[data$name=="Israel"] <- 'ISR'
data$code[data$name=="Israel and Occupied Territories**"] <- 'ISR'
data$code[data$name=="Israel, pre-1967 borders"] <- 'ISR'
data$code[data$name=="Italy"] <- 'ITA'
data$code[data$name=="Jamaica"] <- 'JAM'
data$code[data$name=="Japan"] <- 'JPN'
data$code[data$name=="Jordan"] <- 'JOR'
data$code[data$name=="Kazakhstan"] <- 'KZK'
data$code[data$name=="Kenya"] <- 'KEN'
data$code[data$name=="Korea, North"] <- 'PRK'
data$code[data$name=="North Korea"] <- 'PRK'
data$code[data$name=="People's Republic of Korea"] <- 'PRK'
data$code[data$name=="Korea North"] <- 'PRK'
data$code[data$name=="Korea, Dem. Rep."] <- 'PRK'
data$code[data$name=="North Korea (Democratc People's Republic of Korea)"] <- 'PRK'
data$code[data$name=="Korea, Dem. Rep. (N)"] <- 'PRK'
data$code[data$name=="Korea, Democratic People's Republic of"] <- 'PRK'
data$code[data$name=="Korea, South"] <- 'ROK'
data$code[data$name=="South Korea"] <- 'ROK'
data$code[data$name=="Korea South"] <- 'ROK'
data$code[data$name=="Republic of Korea"] <- 'ROK'
data$code[data$name=="Korea, Rep."] <- 'ROK'
data$code[data$name=="South Korea (Republic of Korea)"] <- 'ROK'
data$code[data$name=="Korea"] <- 'ROK'
data$code[data$name=="Korea, Rep. (S)"] <- 'ROK'
data$code[data$name=="Korea, Republic of"] <- 'ROK'
data$code[data$name=="Kuwait"] <- 'KUW'
data$code[data$name=="Kyrgyzstan"] <- 'KYR'
data$code[data$name=="Kyrgyz Republic"] <- 'KYR'
data$code[data$name=="Laos"] <- 'LAO'
data$code[data$name=="Lao PDR"] <- 'LAO'
data$code[data$name=="Lao P.D.R."] <- 'LAO'
data$code[data$name=="Lao, PDR"] <- 'LAO'
data$code[data$name=="Latvia"] <- 'LAT'
data$code[data$name=="Lebanon"] <- 'LEB'
data$code[data$name=="Lesotho"] <- 'LES'
data$code[data$name=="Liberia"] <- 'LBR'
data$code[data$name=="Libya"] <- 'LIB'
data$code[data$name=="Libyan Arab Jamahiriya"] <- 'LIB'
data$code[data$name=="Lithuania"] <- 'LIT'
data$code[data$name=="Luxembourg"] <- 'LUX'
data$code[data$name=="Macedonia"] <- 'MAC'
data$code[data$name=="Macedonia, FYR"] <- 'MAC'
data$code[data$name=="FYR Macedonia"] <- 'MAC'
data$code[data$name=="Madagascar"] <- 'MAG'
data$code[data$name=="Malawi"] <- 'MAW'
data$code[data$name=="Malaysia"] <- 'MAL'
data$code[data$name=="Maldives"] <- 'MAD'
data$code[data$name=="Mali"] <- 'MLI'
data$code[data$name=="Malta"] <- 'MLT'
data$code[data$name=="Mauritania"] <- 'MAA'
data$code[data$name=="Mauritius"] <- 'MAS'
data$code[data$name=="Mexico"] <- 'MEX'
data$code[data$name=="Moldova"] <- 'MLD'
data$code[data$name=="Mongolia"] <- 'MON'
data$code[data$name=="Montenegro"] <- 'MNE'
data$code[data$name=="Morocco"] <- 'MOR'
data$code[data$name=="Mozambique"] <- 'MZM'
data$code[data$name=="Namibia"] <- 'NAM'
data$code[data$name=="Nepal"] <- 'NEP'
data$code[data$name=="Netherlands"] <- 'NTH'
data$code[data$name=="New Zealand"] <- 'NEW'
data$code[data$name=="Nicaragua"] <- 'NIC'
data$code[data$name=="Nigeria"] <- 'NIG'
data$code[data$name=="Niger"] <- 'NIR'
data$code[data$name=="Norway"] <- 'NOR'
data$code[data$name=="Oman"] <- 'OMA'
data$code[data$name=="Panama"] <- 'PAN'
data$code[data$name=="Pakistan" & data$year >= 1972] <- 'PAK'
data$code[data$name=="Pakistan" & data$year < 1972] <- 'PKS'
data$code[data$name=="Papua New Guinea"] <- 'PNG'
data$code[data$name=="Paraguay"] <- 'PAR'
data$code[data$name=="Peru"] <- 'PER'
data$code[data$name=="Philippines"] <- 'PHI'
data$code[data$name=="Poland"] <- 'POL'
data$code[data$name=="Portugal"] <- 'POR'
data$code[data$name=="Qatar"] <- 'QAT'
data$code[data$name=="Romania"] <- 'RUM'
data$code[data$name=="Russia"] <- 'RUS'
data$code[data$name=="Russian Federation"] <- 'RUS'
data$code[data$name=="Soviet Union"] <- 'USS'
data$code[data$name=="USSR"] <- 'USS'
data$code[data$name=="USSR(Soviet Union)"] <- 'USS'
data$code[data$name=="U.S.S.R."] <- 'USS'
data$code[data$name=="Rwanda"] <- 'RWA'
data$code[data$name=="Sao Tome and Principe"] <- 'STP'
data$code[data$name=="Saudi Arabia"] <- 'SAU'
data$code[data$name=="Senegal"] <- 'SEN'
data$code[data$name=="Sierra Leone"] <- 'SIE'
data$code[data$name=="Singapore"] <- 'SIN'
data$code[data$name=="Slovakia"] <- 'SLO'
data$code[data$name=="Slovak Republic"] <- 'SLO'
data$code[data$name=="Slovenia"] <- 'SLV'
data$code[data$name=="Solomon Islands"] <- 'SOL'
data$code[data$name=="Somalia"] <- 'SOM'
data$code[data$name=="South Africa"] <- 'SAF'
data$code[data$name=="Spain"] <- 'SPN'
data$code[data$name=="Sri Lanka"] <- 'SRI'
data$code[data$name=="Sudan"] <- 'SUD'
data$code[data$name=="South Sudan"] <- 'SSD'
data$code[data$name=="Suriname"] <- 'SUR'
data$code[data$name=="Swaziland"] <- 'SWA'
data$code[data$name=="Sweden"] <- 'SWD'
data$code[data$name=="Switzerland"] <- 'SWZ'
data$code[data$name=="Syria"] <- 'SYR'
data$code[data$name=="Syrian Arab Republic"] <- 'SYR'
data$code[data$name=="Taiwan"] <- 'TAW'
data$code[data$name=="Taiwan Province of China"] <- 'TAW'
data$code[data$name=="Taiwan, China"] <- 'TAW'
data$code[data$name=="Tajikistan"] <- 'TAJ'
data$code[data$name=="Tanzania"] <- 'TAZ'
data$code[data$name=="Thailand"] <- 'THI'
data$code[data$name=="Togo"] <- 'TOG'
data$code[data$name=="Trinidad"] <- 'TRI'
data$code[data$name=="Trinidad and Tobago"] <- 'TRI'
data$code[data$name=="Trinidad & Tobago"] <- 'TRI'
data$code[data$name=="Tunisia"] <- 'TUN'
data$code[data$name=="Turkey"] <- 'TUR'
data$code[data$name=="Turkmenistan"] <- 'TKM'
data$code[data$name=="Uganda"] <- 'UGA'
data$code[data$name=="Ukraine"] <- 'UKR'
data$code[data$name=="United Arab Emirates"] <- 'UAE'
data$code[data$name=="UAE"] <- 'UAE'
data$code[data$name=="United Kingdom"] <- 'UK '
data$code[data$name=="United States"] <- 'USA'
data$code[data$name=="United States of America"] <- 'USA'
data$code[data$name=="Uruguay"] <- 'URU'
data$code[data$name=="Uzbekistan"] <- 'UZB'
data$code[data$name=="Venezuela"] <- 'VEN'
data$code[data$name=="Venezuela, RB"] <- 'VEN'
data$code[data$name=="Vietnam"] <- 'VIE'
data$code[data$name=="Viet Nam"] <- 'VIE'
data$code[data$name=="Vietnam, Socialist Republic of"] <- 'VIE'
data$code[data$name=="North Vietnam"] <- 'DRV'
data$code[data$name=="Democratic Republic of Vietnam"] <- 'DRV'
data$code[data$name=="DRVN"] <- 'DRV'
data$code[data$name=="Vietnam, North"] <- 'DRV'
data$code[data$name=="Vietnam North"] <- 'DRV'
data$code[data$name=="Vietnam, N."] <- 'DRV'
data$code[data$name=="South Vietnam"] <- 'RVN'
data$code[data$name=="Republic of Vietnam"] <- 'RVN'
data$code[data$name=="Vietnam, South"] <- 'RVN'
data$code[data$name=="Vietnam South"] <- 'RVN'
data$code[data$name=="Vietnam, S."] <- 'RVN'
data$code[data$name=="Yemen"] <- 'YEM'
data$code[data$name=="Yemen, Rep."] <- 'YEM'
data$code[data$name=="Yemen Arab Republic" & data$year>=1990] <- 'YEM'
data$code[data$name=="North Yemen"] <- 'YAR'
data$code[data$name=="Yemen, North"] <- 'YAR'
data$code[data$name=="Yemen North"] <- 'YAR'
data$code[data$name=="Yemen Arab Republic"] <- 'YAR'
data$code[data$name=="Yemen, N."] <- 'YAR'
data$code[data$name=="Yemen Arab Republic; N. Yemen"] <- 'YAR'
data$code[data$name=="South Yemen"] <- 'YPR'
data$code[data$name=="Yemen, South"] <- 'YPR'
data$code[data$name=="Yemen South"] <- 'YPR'
data$code[data$name=="Yemen People's Republic"] <- 'YPR'
data$code[data$name=="SouthYemen"] <- 'YPR'
data$code[data$name=="Yemen, S."] <- 'YPR'
data$code[data$name=="Yemen People's Republic; S. Yemen"] <- 'YPR'
data$code[data$name=="Yemen PDR (South)"] <- 'YPR'
data$code[data$name=="Yugoslavia"] <- 'YGS'
data$code[data$name=="Yugoslavia" & data$year >= 1992] <- 'YGS'
data$code[data$name=="Serbia and Montenegro" & data$year >= 1992] <- 'YGS'
data$code[data$name=="Yugoslavia, Fed. Rep." & data$year >= 1992] <- 'YGS'
data$code[data$name=="Federal Republic of Yugoslavia" & data$year >= 1992] <- 'YGS'
data$code[data$name=="Yugoslavia (Serbia & Montenegro)"] <- 'YGS'
data$code[data$name=="Yugoslavia, FR (Serbia/Montenegro)"] <- 'YGS'
data$code[data$name=="Yugoslavia, Federal Republic of"] <- 'YGS'
data$code[data$name=="Yugoslavia" & data$year < 1992] <- 'YUG'
data$code[data$name=="Former Yugoslavia" & data$year < 1992] <- 'YUG'
data$code[data$name=="Yugoslavia, Fed. Rep." & data$year < 1992] <- 'YUG'
data$code[data$name=="Yugoslavia, FPR"] <- 'YUG'
data$code[data$name=="Serbia"] <- 'SRB'
data$code[data$name=="Yugoslavia" & data$year > 2005] <- 'SRB'
data$code[data$name=="Zambia"] <- 'ZAM'
data$code[data$name=="Zimbabwe"] <- 'ZIM'
data$code[data$name=="Yemen"] <- 'YEM'
data$code[data$name=="Kosovo"] <- 'KOS'
data$code[data$name=="Palestinian Authority"] <- 'PAL'
